configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.1.0+sha512-vsCchpE+K6g67YdDYYBCVQQFpfVFuVV423CCBbUEBm7FmWg/MI0Keuhkb6bjWpWaITE1PMSmcsrXbHv9FPFloA==

onlyBuiltDependencies:
    - core-js-pure
    - simple-git-hooks

trustPolicyExclude:
    - "@next/env@12.3.7"
    - "@next/eslint-config-next@12.3.7"
    - "@next/eslint-plugin-next@12.3.7"
    - eslint-config-next@12.3.7
    - eslint-config-prettier@8.10.2
    - eslint-plugin-prettier@4.2.5
    - next@12.3.7
    - semver@6.3.1
