configDependencies:
    "@obusk/pnpm-plugin-defaults": latest

minimumReleaseAgeExclude:
    - next
    - "@next/*"
    - eslint-config-next
    - "@obusk/eslint-config-next"

allowBuilds:
    "@parcel/watcher": true
    sharp: true
    simple-git-hooks@2.14.0: true
    unrs-resolver: true

overrides:
    "@types/react": 19.3.0
    "@types/react-dom": 19.3.0

trustPolicyExclude:
    - semver@6.3.1
